name: meteo
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - meteofetch>=0.5.6
  - meteole>=0.2.6
  - xarray>=2026.4.0
  - pandas>=3.0.2
  - matplotlib>=3.10.9
  - cartopy>=0.25.0
  - cfgrib>=0.9.15.1
  - eccodes>=2.47.0
  - numpy>=2.4.3
